apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: qf8fe5x3z-nodejs-gitops
  description: This is GitOps manifest for qf8fe5x3z-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=qf8fe5x3z-nodejs
    backstage.io/kubernetes-id: qf8fe5x3z-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: qf8fe5x3z-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:qf8fe5x3z-nodejs
