apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qf8fe5x3z-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qf8fe5x3z-nodejs 
  name: qf8fe5x3z-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: qf8fe5x3z-nodejs 
